config/routes.rb
Rails.application.routes.draw do
  namespace :statistics do
    get('records/search')
    post('records/search')
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #@registries = Registry.find(:all, :include => [:statistics_version, :statistics_summary])
    @registries = Registry.all
    @records    = Statistics::Record.new
    @countries  = Country.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_iptables_ipv4_dialog.html.erb
<div id="iptables_ipv4_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= content_tag(:h4, 'IPv4 アドレス', { :class => 'modal-title' }) %>
      </div>
      <div class="modal-body">
        <%= text_area_tag(:iptv4_command, nil, {:size => '80x10', :class => 'form-control'}) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/welcome/_select_country_dialog.html.erb
<div id="country_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= content_tag(:h4, 'カントリーコード選択', { :class => 'modal-title' }) %>
      </div>
      <div class="modal-body">
        <dl id="type_select">
          <dt>アドレスタイプ:</dt>
          <dd>
            <label><input type="checkbox" value="asn" name="addr_type" />ASN</label>
            <label><input type="checkbox" value="ipv4" name="addr_type" />IPv4</label>
            <label><input type="checkbox" value="ipv6" name="addr_type" />IPv6</label>
          </dd>
        </dl>
        <table class="table table-striped">
          <tbody>
            <% @countries.each do |country| %>
              <tr>
                <td>
                  <%= button_tag('ADD', {:id => "country_add_#{country.alpha2}", :name => 'country_add', :class => 'btn btn-default btn-xs', :type => :button}) %>
                  <input type="hidden" value="<%= country.alpha2 %>" />
                </td>
                <td><img alt="" src="/assets/flags/shiny/16/<%= country.flag_filename %>.png" /></td>
                <td name="country_code"><%= country.alpha2 %></td>
                <td><%= country.country_name %>(<%= country.country_name_ja %>)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/welcome/index.html.erb
<section class="row">
  <div id="search" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <%= form_for(@records, :url => statistics_records_search_path(:format => :json), :html => {:class => 'form-inline', :id => 'search_statistics_record', :remote => true, :role => :form}) do |f| %>
      <div class="form-group">
        <label class="sr-only" for="statistics_record_start_addr">Keywords</label>
        <%= f.text_field(:start_addr, {:class => 'form-control', :placeholder => 'Keywords', :title => 'キーワードはIPv4、ASNコード、カントリーコード(ISO3166-1 alpha-2)を入力可能です。<br />複数のキーワードをカンマ区切りで複数入力できます。'}) %>
      </div>
      <%= button_tag('Country Code', { :class => 'btn btn-default', :type => :button, :data => { :toggle => 'modal', :target => '#country_modal'}}) %>
      <%= f.submit('Search', { :class => 'btn btn-primary' }) %>
    <% end %>
  </div>
</section>

<section class="row">
  <div id="data" class="col-lg-12 col-md-12 col-sm-12 col-xs-12"></div>
</section>

<!-- dialog -->
<%= render('welcome/select_country_dialog') %>
<%= render('welcome/iptables_ipv4_dialog') %>